server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # SPA fallback (React Router)
  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(webmanifest|manifest)$ {
    add_header Content-Type application/manifest+json;
  }

  # Cache static assets aggressively
  location /static/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}

