/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a comment on a task
     * @description Creates a new comment on a task. User must own the task or have assigned it.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Comment creation data */
      requestBody: {
        content: {
          'application/json': components['schemas']['handlers.CreateCommentRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Comment'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/comments/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a comment by ID
     * @description Retrieves a specific comment by its ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Comment ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Comment'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    /**
     * Update a comment
     * @description Updates an existing comment. Only the comment author can update it.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Comment ID */
          id: number;
        };
        cookie?: never;
      };
      /** @description Comment update data */
      requestBody: {
        content: {
          'application/json': components['schemas']['handlers.UpdateCommentRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Comment'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    post?: never;
    /**
     * Delete a comment
     * @description Deletes a comment by its ID. Only the comment author can delete it.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Comment ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/group-invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List received invitations
     * @description Returns pending group invitations where the authenticated user is the invitee.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.GroupInvitationListItem'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/group-invitations/{id}/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Accept group invitation */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Invitation ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/group-invitations/{id}/decline': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Decline group invitation */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Invitation ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/groups': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List my groups
     * @description Returns all groups where the authenticated user is a member.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.GroupListItemResponse'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /** Create a group */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Group name */
      requestBody: {
        content: {
          'application/json': components['schemas']['handlers.CreateGroupRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Group'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/groups/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get group details */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Group ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.GroupDetailResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    /** Update group name */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Group ID */
          id: number;
        };
        cookie?: never;
      };
      /** @description New name */
      requestBody: {
        content: {
          'application/json': components['schemas']['handlers.UpdateGroupRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Group'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    post?: never;
    /** Delete a group */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Group ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/groups/{id}/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Invite user to group
     * @description Creates a pending invitation; the user must accept to join. Cannot invite existing members.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Group ID */
          id: number;
        };
        cookie?: never;
      };
      /** @description User to invite */
      requestBody: {
        content: {
          'application/json': components['schemas']['handlers.InviteUserRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.GroupInvitation'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/groups/{id}/invitations/{invitation_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Cancel group invitation */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Group ID */
          id: number;
          /** @description Invitation ID */
          invitation_id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/groups/{id}/members/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove group member
     * @description Any member can remove another member or leave by passing their own user ID.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Group ID */
          id: number;
          /** @description User ID to remove */
          user_id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/debug': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get notification debug info
     * @description Returns debug information about the current user's notification settings and recent tasks
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/in-app': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List in-app notifications
     * @description Returns in-app notifications (e.g. group invites). Use unread_only=true for unread only.
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number (default: 1) */
          page?: number;
          /** @description Items per page (default: 20, max: 100) */
          limit?: number;
          /** @description Only unread notifications */
          unread_only?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.PaginatedInAppNotificationsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/in-app/read-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark all notifications as read */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/in-app/unread-count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Unread in-app notification count
     * @description Returns how many in-app notifications are unread (for badge display).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.UnreadCountResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/in-app/{id}/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Mark notification as read */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Notification ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/notifications/test': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Test notifications
     * @description Manually triggers a notification check. Useful for testing without waiting for the scheduler. Check server logs for detailed information.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tags': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List user tags
     * @description Retrieves all tags for the authenticated user
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Tag'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a new tag
     * @description Creates a new custom tag for the authenticated user
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Tag creation data */
      requestBody: {
        content: {
          'application/json': components['schemas']['handlers.CreateTagRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Tag'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tags/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a tag by ID
     * @description Retrieves a specific tag by its ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Tag ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Tag'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    /**
     * Update a tag
     * @description Updates an existing tag
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Tag ID */
          id: number;
        };
        cookie?: never;
      };
      /** @description Tag update data */
      requestBody: {
        content: {
          'application/json': components['schemas']['handlers.UpdateTagRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Tag'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    post?: never;
    /**
     * Delete a tag
     * @description Deletes a tag by its ID
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Tag ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tasks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List user tasks
     * @description Retrieves paginated tasks for the authenticated user with optional filters, search, and sorting
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number (default: 1) */
          page?: number;
          /** @description Items per page (default: 10, max: 100) */
          limit?: number;
          /** @description Filter by task type (casa, trabalho, lazer, saude) */
          type?: string;
          /** @description Filter by completion status */
          completed?: boolean;
          /** @description Search in title and description */
          search?: string;
          /** @description Filter tasks with due date from (ISO 8601 format) */
          due_date_from?: string;
          /** @description Filter tasks with due date to (ISO 8601 format) */
          due_date_to?: string;
          /** @description Filter by period (overdue, today, this_week, this_month) */
          period?: string;
          /** @description Filter by user ID who assigned the task */
          assigned_by?: number;
          /** @description Filter by priority (baixa, media, alta, urgente) */
          priority?: string;
          /** @description Filter by tag IDs, comma-separated (e.g. 1,2,3) */
          tag_ids?: string;
          /** @description Sort field (created_at, due_date, title, priority) */
          sort_by?: string;
          /** @description Sort order (asc, desc) */
          order?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['services.PaginatedTasksResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a new task
     * @description Creates a new task for the authenticated user or assigns it to another user
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Task creation data */
      requestBody: {
        content: {
          'application/json': components['schemas']['handlers.CreateTaskRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Task'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tasks/assigned': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List tasks assigned by user
     * @description Retrieves paginated tasks that were created/assigned by the authenticated user to other users. This allows users to follow tasks they created for others.
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number (default: 1) */
          page?: number;
          /** @description Items per page (default: 10, max: 100) */
          limit?: number;
          /** @description Filter by task type (casa, trabalho, lazer, saude) */
          type?: string;
          /** @description Filter by completion status */
          completed?: boolean;
          /** @description Search in title and description */
          search?: string;
          /** @description Filter tasks with due date from (ISO 8601 format) */
          due_date_from?: string;
          /** @description Filter tasks with due date to (ISO 8601 format) */
          due_date_to?: string;
          /** @description Filter by period (overdue, today, this_week, this_month) */
          period?: string;
          /** @description Filter by priority (baixa, media, alta, urgente) */
          priority?: string;
          /** @description Filter by tag IDs, comma-separated (e.g. 1,2,3) */
          tag_ids?: string;
          /** @description Sort field (created_at, due_date, title, priority) */
          sort_by?: string;
          /** @description Sort order (asc, desc) */
          order?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['services.PaginatedTasksResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tasks/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a task by ID
     * @description Retrieves a specific task by its ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Task'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    /**
     * Update a task
     * @description Updates an existing task
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task ID */
          id: number;
        };
        cookie?: never;
      };
      /** @description Task update data */
      requestBody: {
        content: {
          'application/json': components['schemas']['handlers.UpdateTaskRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Task'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    post?: never;
    /**
     * Delete a task
     * @description Deletes a task by its ID
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tasks/{id}/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get comments for a task
     * @description Retrieves all comments for a specific task. User must own the task or have assigned it.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.Comment'][];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tasks/{id}/share': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Share a task with users
     * @description Adds users to the task's shared list. Only the owner can share. Target users must be members of at least one group in common with the owner.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task ID */
          id: number;
        };
        cookie?: never;
      };
      /** @description User IDs to share with */
      requestBody: {
        content: {
          'application/json': components['schemas']['handlers.ShareTaskRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tasks/{id}/share/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Unshare a task with a user
     * @description Removes the given user from the task's shared list. Only the task owner can unshare.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Task ID */
          id: number;
          /** @description User ID to remove from shared list */
          user_id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List users
     * @description Default: users who share at least one group (for share/assign). Use scope=invite to list users available to invite (optional group_id to exclude members and pending invites).
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number (default: 1) */
          page?: number;
          /** @description Items per page (default: 10, max: 100) */
          limit?: number;
          /** @description invite — all users for group invite picker */
          scope?: string;
          /** @description Group ID when scope=invite (excludes members and pending) */
          group_id?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.PaginatedUsersResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user profile
     * @description Returns the authenticated user's profile including notification settings
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['models.User'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/notifications-enabled': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update notifications enabled
     * @description Updates the notifications enabled setting for the authenticated user
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Notifications enabled */
      requestBody: {
        content: {
          'application/json': components['schemas']['handlers.UpdateNotificationsEnabledRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/telegram-chat-id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update Telegram chat ID
     * @description Updates the Telegram chat ID for the authenticated user to receive notifications
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Telegram chat ID */
      requestBody: {
        content: {
          'application/json': components['schemas']['handlers.UpdateTelegramChatIDRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.SuccessResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['handlers.ErrorResponse'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    'handlers.CreateCommentRequest': {
      /** @example This is a comment on the task */
      content: string;
      /** @example 1 */
      task_id: number;
    };
    'handlers.CreateGroupRequest': {
      /** @example Equipe */
      name: string;
    };
    'handlers.CreateTagRequest': {
      /**
       * @description Optional: hex color code
       * @example #FF5733
       */
      color: string;
      /** @example Important */
      name: string;
    };
    'handlers.CreateTaskRequest': {
      /** @example Clean all rooms */
      description: string;
      /**
       * @description ISO 8601 format
       * @example 2024-12-31T23:59:59Z
       */
      due_date: string;
      /**
       * @description Optional: task priority
       * @example alta
       * @enum {string}
       */
      priority: 'baixa' | 'media' | 'alta' | 'urgente';
      /** @description Optional: IDs of tags to associate */
      tag_ids: number[];
      /** @example Clean the house */
      title: string;
      /**
       * @example casa
       * @enum {unknown}
       */
      type: 'casa' | 'trabalho' | 'lazer' | 'saude';
      /**
       * @description Optional: if provided, assign to another user
       * @example 2
       */
      user_id: number;
    };
    'handlers.ErrorResponse': {
      error: string;
      message: string;
    };
    'handlers.GroupDetailResponse': {
      created_by: number;
      id: number;
      is_default: boolean;
      members: components['schemas']['models.UserPublic'][];
      name: string;
      pending_invitations: components['schemas']['models.GroupInvitation'][];
    };
    'handlers.GroupInvitationListItem': {
      created_at: string;
      group: components['schemas']['models.Group'];
      group_id: number;
      id: number;
      invited_by_user: components['schemas']['models.User'];
      invited_by_user_id: number;
      invited_user: components['schemas']['models.User'];
      invited_user_id: number;
      responded_at: string;
      status: components['schemas']['models.GroupInvitationStatus'];
      updated_at: string;
    };
    'handlers.GroupListItemResponse': {
      created_by: number;
      id: number;
      is_default: boolean;
      member_count: number;
      name: string;
    };
    'handlers.InviteUserRequest': {
      /** @example 2 */
      user_id: number;
    };
    'handlers.PaginatedInAppNotificationsResponse': {
      limit: number;
      notifications: components['schemas']['models.UserNotification'][];
      page: number;
      total: number;
      total_pages: number;
    };
    'handlers.PaginatedUsersResponse': {
      limit: number;
      page: number;
      total: number;
      total_pages: number;
      users: components['schemas']['models.UserPublic'][];
    };
    'handlers.ShareTaskRequest': {
      /**
       * @example [
       *       2,
       *       3,
       *       4
       *     ]
       */
      user_ids: number[];
    };
    'handlers.SuccessResponse': {
      data: unknown;
      message: string;
    };
    'handlers.UnreadCountResponse': {
      count: number;
    };
    'handlers.UpdateCommentRequest': {
      /** @example Updated comment text */
      content: string;
    };
    'handlers.UpdateGroupRequest': {
      /** @example Equipe atualizada */
      name: string;
    };
    'handlers.UpdateNotificationsEnabledRequest': {
      /** @example true */
      notifications_enabled: boolean;
    };
    'handlers.UpdateTagRequest': {
      /** @example #33FF57 */
      color: string;
      /** @example Updated Tag */
      name: string;
    };
    'handlers.UpdateTaskRequest': {
      /** @example true */
      completed: boolean;
      /** @example Updated description */
      description: string;
      /** @example 2024-12-31T23:59:59Z */
      due_date: string;
      /**
       * @example urgente
       * @enum {string}
       */
      priority: 'baixa' | 'media' | 'alta' | 'urgente';
      /** @description Optional: nil = no change, [] = remove all, [1,2] = set tags */
      tag_ids: number[];
      /** @example Updated title */
      title: string;
      /**
       * @example trabalho
       * @enum {unknown}
       */
      type: 'casa' | 'trabalho' | 'lazer' | 'saude';
    };
    'handlers.UpdateTelegramChatIDRequest': {
      /**
       * @description Telegram chat ID (must be numeric string, null to remove). User must send a message to the bot first.
       * @example 123456789
       */
      telegram_chat_id: string;
    };
    'models.Comment': {
      /** @description Comment text */
      content: string;
      created_at: string;
      id: number;
      task: components['schemas']['models.Task'];
      /** @description ID of the task this comment belongs to */
      task_id: number;
      updated_at: string;
      user: components['schemas']['models.User'];
      /** @description ID of the user who created the comment */
      user_id: number;
    };
    'models.Group': {
      created_at: string;
      created_by: number;
      creator: components['schemas']['models.User'];
      id: number;
      is_default: boolean;
      members: components['schemas']['models.User'][];
      name: string;
      updated_at: string;
    };
    'models.GroupInvitation': {
      created_at: string;
      group: components['schemas']['models.Group'];
      group_id: number;
      id: number;
      invited_by_user: components['schemas']['models.User'];
      invited_by_user_id: number;
      invited_user: components['schemas']['models.User'];
      invited_user_id: number;
      responded_at: string;
      status: components['schemas']['models.GroupInvitationStatus'];
      updated_at: string;
    };
    /** @enum {string} */
    'models.GroupInvitationStatus': 'pending' | 'accepted' | 'declined' | 'cancelled';
    /** @enum {string} */
    'models.Priority': 'baixa' | 'media' | 'alta' | 'urgente';
    'models.Tag': {
      /** @description Hex color code (e.g., #FF5733) */
      color: string;
      created_at: string;
      id: number;
      name: string;
      tasks: components['schemas']['models.Task'][];
      updated_at: string;
      user: components['schemas']['models.User'];
      /** @description Tags are user-specific */
      user_id: number;
    };
    'models.Task': {
      /** @description ID of the user who created/assigned the task (nil if created by the user themselves) */
      assigned_by: number;
      assigned_by_user: components['schemas']['models.User'];
      /** @description Comments on the task */
      comments: components['schemas']['models.Comment'][];
      completed: boolean;
      created_at: string;
      description: string;
      /** @description Deadline for task completion */
      due_date: string;
      id: number;
      /** @description Task priority */
      priority: components['schemas']['models.Priority'];
      /** @description Users with whom the task is shared (no limit) */
      shared_with: components['schemas']['models.User'][];
      /** @description Tags associated with the task */
      tags: components['schemas']['models.Tag'][];
      title: string;
      type: components['schemas']['models.TaskType'];
      updated_at: string;
      user: components['schemas']['models.User'];
      /** @description ID of the user responsible for the task (owner) */
      user_id: number;
    };
    /** @enum {string} */
    'models.TaskType': 'casa' | 'trabalho' | 'lazer' | 'saude';
    'models.User': {
      created_at: string;
      email: string;
      id: number;
      /** @description Opt-in notifications */
      notifications_enabled: boolean;
      /** @description Telegram chat ID for notifications */
      telegram_chat_id: string;
      terms_accepted_at: string;
      updated_at: string;
      username: string;
    };
    'models.UserNotification': {
      created_at: string;
      id: number;
      payload: string;
      read: boolean;
      type: components['schemas']['models.UserNotificationType'];
      updated_at: string;
      user_id: number;
    };
    /** @enum {string} */
    'models.UserNotificationType': 'group_invite';
    'models.UserPublic': {
      created_at: string;
      id: number;
      updated_at: string;
      username: string;
    };
    'services.PaginatedTasksResponse': {
      limit: number;
      page: number;
      tasks: components['schemas']['models.Task'][];
      total: number;
      total_pages: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
